sudo: required
services:
- docker
before_install:
- docker build -t tagmon/docker-react -f Dockerfile.dev .
script:
- docker run -e CI=true tagmon/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "frontent"
  env: "Frontent-env"
  bucket_name: "elasticbeanstalk-eu-west-3-416497172425"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
